### ISSUE TITLE
QA_Linear Perceptron Learning_Further Readings_p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/pattern-recognition-iiith#14] opened 2016-04-18 10:19 UTC
Defect Description :
In Further Readings page of "Linear Perceptron Learning " experiment,  when we click on the link Perceptron Algorithm at CMU , it is redirecting to an error page (404) instead it should redirect to a new page with the selected link 

Actual Result :
In Further Readings page of "Linear Perceptron Learning " experiment, when we click on the link Perceptron Algorithm at CMU , it is redirecting to an error page (404)

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/pattern-recognition-iiith/blob/master/test-cases/integration_test-cases/Linear%20Perceptron%20Learning/Linear%20Perceptron%20Learning_12_Further%20Readings_p1.org

Attachment: 
![pr3](https://cloud.githubusercontent.com/assets/14869397/14601297/05eea202-057f-11e6-83da-899cfd5847c6.png)

**Comment by BSravanthi** [comment] 2016-06-29 06:10
After changing the UI conversion from UI 1.0 to UI 3.0, Further Readings link needs to be added.

**Comment by sravanthimodepu** [comment] 2016-07-12 04:38
Link is updated and the issue is fixed now.

**Comment by BSravanthi** [comment] 2016-07-22 09:44
Closed #14

**Closed by BSravanthi** 2016-07-22 09:44 UTC
Labels: Category: Functionality, Developed By: VLEAD, Release Number: Production, Severity: S1, Status : Resolved
